# Continuous Integration tests
name: NUbots CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Triggers on PRs to any branch
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build LLVM
  build_llvm:
    name: "Build LLVM"
    uses: mrwerdo/nubots/.github/workflows/build_part_of_image.yaml@0e80f6b52a1f545d18ec012c4f3e94908acb0594
    with:
      target: llvm
      tags: mrwerdo/nubots:llvm
      cache_from: |
        type=registry,ref=mrwerdo/nubots:generic
        type=inline
    secrets:
      docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build_intel_graphics_compiler_and_compute_runtime:
    name: "Build Intel Graphics Compiler and Compute Runtime"
    uses: mrwerdo/nubots/.github/workflows/build_part_of_image.yaml@0e80f6b52a1f545d18ec012c4f3e94908acb0594
    needs: build_llvm
    with:
      target: intel-graphics-compiler-and-compute-runtime
      tags: mrwerdo/nubots:intel-graphics-compiler-and-compute-runtime
      cache_from: |
        type=registry,ref=mrwerdo/nubots:llvm
        type=registry,ref=mrwerdo/nubots:generic
        type=inline
    secrets:
      docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build_openblas:
    name: "Build OpenBLAS"
    uses: mrwerdo/nubots/.github/workflows/build_part_of_image.yaml@0e80f6b52a1f545d18ec012c4f3e94908acb0594
    with:
      target: openblas
      tags: mrwerdo/nubots:openblas
      cache_from: |
        type=registry,ref=mrwerdo/nubots:generic
        type=inline
    secrets:
      docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build_other_dependencies:
    name: "Build Other Dependencies"
    uses: mrwerdo/nubots/.github/workflows/build_part_of_image.yaml@0e80f6b52a1f545d18ec012c4f3e94908acb0594
    with:
      target: other-dependencies
      tags: mrwerdo/nubots:other-dependencies
      cache_from: |
        type=registry,ref=mrwerdo/nubots:generic
        type=inline
    secrets:
      docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build_docker:
    name: "Build Docker Image"
    uses: mrwerdo/nubots/.github/workflows/build_part_of_image.yaml@0e80f6b52a1f545d18ec012c4f3e94908acb0594
    needs:
      - build_llvm
      - build_intel_graphics_compiler_and_compute_runtime
      - build_openblas
      - build_other_dependencies
    with:
      target: final-image
      tags: mrwerdo/nubots:pull-request-${{ github.event.number }}
      cache_from: |
        type=registry,ref=mrwerdo/nubots:generic
        type=registry,ref=mrwerdo/nubots:intel-graphics-compiler-and-compute-runtime
        type=registry,ref=mrwerdo/nubots:llvm
        type=registry,ref=mrwerdo/nubots:openblas
        type=registry,ref=mrwerdo/nubots:other-dependencies
        type=inline
    secrets:
      docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  # Build the codebase
  build_nubots:
    name: "Build and test NUbots"

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: build_docker

    # Run on the container we just built
    container:
      image: mrwerdo/nubots:pull-request-${{ github.event.number }}
      options: --user 0:0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Cancels previously running jobs for this workflow
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prepare Build Directory
        run: mkdir -p ../build

      - name: Configure the code
        run: ./b configure -- -DBUILD_TESTS=ON -DCI_BUILD=ON

      - name: Build the code
        run: ./b build

      - name: Test the code
        run: ./b tests run
